@host = http://localhost:5283

### Создать правило
POST {{host}}/api/rules
Content-Type: application/json

{
  "ruleName": "Постановка на миграционный учет",
  "targetDocs": ["Документ, подтверждающий постановку на миграционный учет"],
  "guidanceDescription": "Обратитесь к лицу, у которого проживаете",
  "refusal": "",
  "orgNames": ["УМВД"],
  "orgAddresses": ["через портал госуслуг"],
  "daysList": [90, 30, 15, 7],
  "purposeNamesList": [
    ["Работа", "Учёба"],
    ["Работа"],
    ["Работа"],
    ["Работа"]
  ],
  "citizenshipNamesList": [
    ["Белоруссия", "Украина"],
    ["Киргизия", "Казахстан", "Армения"],
    ["Таджикистан", "Узбекистан"],
    ["Все остальные"]
  ],
  "propertyNames": [
    [],
    ["Дополнительное условие"],
    [],
    []
  ],
  "propertyValues": [
    [],
    ["ранее уже состоял на миграционном учёте"],
    [],
    []
  ]
}

### Получить правило по ID
GET {{host}}/api/rules/1
Accept: application/json